### PR TITLE
added missing test

### PR DESCRIPTION
**Pull request by Rafael-G-C**
Here's the test to check that it reads a functional and geometry from a file
@bast @robertodr

### CODE REVIEW

**Comment by bast** [comment]
I think we should make this test automatic. Can you describe how you run it and how you check that it works? Then I can give hints on how we can test it automatically.

**Comment by Rafael-G-C** [comment]
On line 17 I append the **test.txt** I made and let the program run
once it outputs the results I modify line 17 to append one of the examples and run it 
Finally I compare the results manually

**Comment by bast** [comment]
Sorry for this question but line 17 of which file? I will help you then to set up an automatic test but first I want to learn how you run this.

**Comment by Rafael-G-C** [comment]
It is my fault for not explaining well. the script im talking about is
.../pyDFTD3/dftd3/__main __.py 
this script gets the input file from the users command line and calls .../pyDFTD3/dftd3/dftd3.py where it will run the D3 calculation 

I added line 17 `sys.argv.append("/home/kilimanjaro/Documents/Nor/pyDFTD3/test.txt")`  to append the path to the test file instead of getting it from the command line 

- I did this for debugging purposes

- This is also the line I edit in order to test, I change from _/pyDFTD3/test.txt_ to _/pyDFTD3/examples/formic_acid_dimer.com_

once the program is running the dftd3.py code, it goes to the main function `def main():` it will look for any parameters (from the command line input) and reach the line
` if sys.argv[i].split(".")[1] == "out" ...` 
where it will check the extension of the file, I added the line  `sys.argv[i].split(".")[1] == "txt"` for it to be able to get the simple input then it reaches line
`if len(file.split(".txt"))>1: fileData = get_simple_data(file)` and goes to .../pyDFTD3/dftd3/ccParse.py to extract the info from the class `class get_simple_data:`
once it extracts it it runs the D3 calculation

**Comment by bast** [comment]
Next step is to modify the code so that we don't have to modify the code to test it. By passing the test input as argument to the code. Once we have that, we can script the testing, once we have that we add the test to GitHub Actions so that we test on each commit.

**Comment by robertodr** [comment]
I have added a test and a github action to test the modifications on this branch. I'll merge and go on with the refactoring we need to move the project forward (JSON input and moving from classes to free functions)

**Pull request merged**
