### PR TITLE
documentation and rearrangement

### PR DESCRIPTION
**Pull request by Rafael-G-C**
the jax functions accepts the atoms (charges) and then the coordinates so I changed the ordering in the d3 function 
added the doc strings mentioned on #2
do tell me if I missed something, I can't shake away the feeling I did

### CODE REVIEW

**Comment by robertodr** [comment]
I think you forgot to update your local version of the master branch before making new changes: many commits which were already merged (in squashed form) are now reappering. I think the following should work to fix the situation:

```bash
$ git checkout master
$ git fetch origin
$ git pull --rebase origin master
$ git checkout -b new-branch
$ git cherry-pick <commit hashes to pick>
$ git push --set-upstream origin new-branch
```

**Comment by Rafael-G-C** [comment]
ooooh I see what I'm doing wrong I'm fetching and pulling the "flat" branch not the "master" branch I thought since the last merge in the master branch was from the flat branch there wouldn't be any difference, and since I'm always pushing the one branch there shouldn't be any problems

**Comment by robertodr** [comment]
Can this be closed?

**Comment by Rafael-G-C** [comment]
yep

**Pull request closed without merging**
