### PR TITLE
Connect testing to new code

### PR DESCRIPTION
**Pull request by bast**
Summary of what happens in this PR:
- Tests now only test the new code (against old reference numbers so functionality is preserved)
- Test time got shorter
- Added the Becke-Johnson damping also to the new code
- Renamed `dftd3` to `dftd3_old`
- Did not remove any code in `dftd3_old`
- There is no command line interface in the new code (see follow-up below)

Follow-up steps for later:
- Decide whether to re-introduce a command line interface in front of the library
- Update README
- Maybe disconnect fork-relation to avoid sending PRs accidentally to upstream
- Remove `examples` since they are not relevant for this code?
- Maybe introduce wrapper functions to simplify the calls when differentiating

### CODE REVIEW

**Comment by bast** [comment]
More follow-up:
- The parameters.csv location is a bit hardcoded and the loading of coefficients and parameters is not elegant

**Comment by robertodr** [comment]
We can disconnect the fork relation. You rewrote the whole thing and there's not much relation anymore anyway 😄 We can update the README to acknowledge the heavy influence of pydftd3.

**Comment by bast** [comment]
I mean I don't mind the fork relation but for a moment I got very confused when after opening the PR form I saw dozens of commits which I didn't do until I noticed that it automatically takes upstream as the destination.

**Review by robertodr — APPROVED** [review]
Looks good to me! I think a wrapper to get derivatives would be good.

**Pull request merged**
