### PR TITLE
Some gradient

### PR DESCRIPTION
**Pull request by Rafael-G-C**
@bast here's the code that returns the error

> TypeError: Gradient only defined for scalar-output functions. Output was [array(0.), array(0.), array(0.), array(0.), array(0.), array(0.), array(0.), array(0.), array(0.), array(0.)].

just run the test as `python3 -m pytest tests/` in the pyDFTD3 folder 
on `line 93` in test_CO2H2_2.py "2" is the hessian
`d3_dervs = D3_derivatives(charges,functional,damping,2,coordinates)`

### CODE REVIEW

**Comment by bast** [comment]
And what we want to find out is: why is the output a list instead of a float?

**Comment by Rafael-G-C** [comment]
Yes, and now that I look at it why it a list zeros

**Comment by bast** [comment]
I think the code fails because the first element in `variables` [here](https://github.com/Rafael-G-C/pyDFTD3/blob/e7fc05e5c7df6bd7b82c43237980fa1dd2199380/dftd3/jax_diff.py#L26) is an array of charges (see [here](https://github.com/Rafael-G-C/pyDFTD3/blob/e7fc05e5c7df6bd7b82c43237980fa1dd2199380/dftd3/jax_diff.py#L60)). I think this is some leftover?

**Comment by Rafael-G-C** [comment]
Okey, might be let's see what's happens when I fix it

**Comment by bast** [comment]
Also in the test I would not start by cycling through all derivatives but start only with very few elements. It takes time to cycle through all of them and right now we will be very happy if already 1 or 2 work which takes a fraction.

**Comment by Rafael-G-C** [comment]
I see so stopping the derivative order loop earlier

**Comment by Rafael-G-C** [comment]
Alright the code can now:
get the gradient, hessian, 3rds and 4rds of the sum of the r6, r8 and repulse interactions in kcal
this line `derivative_orders = list(derivative_orders)[0:1]` is used to cut off the list of derivative orders so we have control of how many we want

**Comment by bast** [comment]
This sounds fantastic!

**Comment by robertodr** [comment]
Really great Rafael, apologies for tardiness, I didn't get email notifications for these changes... I'll try to fix the conflicts with the base branch and get a test going.

**Comment by robertodr** [comment]
Really great Rafael, apologies for tardiness, I didn't get email notifications for these changes... I'll try to fix the conflicts with the base branch and get a test going.

**Comment by robertodr** [comment]
OK, so:
- I have rebased on top of `master` and fixed the conflicts. @Rafael-G-C, before you do any edits locally: `git pull --rebase origin some_gradient`
- The main function (`d3`) accepts 3 arguments: the configuration, the list of charges, the list of coordinates. The configuration is a `dataclass`.
- I have re-enabled the tests for the energy. The reference numbers come from the implementation in LSDALTON.
- I have added tests for the gradient. Again, the reference numbers come from the implementation in LSDALTON, which is analytical, not numerical.
- I have updated the `requirements.txt`, since we officially depend on JAX now. I dropped Windows in the GitHub action.

**Comment by robertodr** [comment]
A word of warning: the gradient test is pretty slow.

**Comment by robertodr** [comment]
The tests should hopefully run slightly faster now (I've removed one of the parametrization levels for the gradient test)

I have also reorganized a bit the code to make it easier (hopefully!) for @ringholm to run the numdiff tests:
1. To run a `n` order derivative calculation: 
    ```bash
    python -m dftd3.dftd3 --damp zero --order 1 examples/formic_acid_dimer.com
    ```
2. This outputs the energy to screen and writes a JSON file with the full input and full output (including the gradient). In Python, you can load the gradient with:
    ```python
    import json
    
    import numpy as np
    
    with open("formic_acid_dimer.json", "r") as f:
           data = json.load(f)

    gradient = np.array(data["formic_acid_dimer"]["output"]["1-st order geometric derivative"])
    ```

**Comment by robertodr** [comment]
Merging so that @ringholm can try the numerical differentiation stuff before the next meeting.

**Pull request merged**
